### ISSUE TITLE
pls make the public transport times like dynamic because it's just the timetable times which isn't very useful when the 601 is 12 minutes late

### ISSUE THREAD

**Issue by the-ethan-wang** [SubjectiveLabs/SubjectiveAPI#3]

**Comment by the-ethan-wang** [comment]
like https://transportnsw.info/trip#/departures?depart=G2153190&type=stop&accessible=false&dateTime=202510011625

**Comment by the-ethan-wang** [comment]
https://transportnsw.info/api/trip/v1/departure-list-request?date=20251001&debug=false&depArrMacro=dep&depType=stopEvents&name=G2153190&time=1625&type=stop&accessible=false

**Comment by circles-png** [comment]
should be fixed in 8732872203e0b296f16f3e6a9dba2688ce818bf5, close this issue if it works

**Comment by the-ethan-wang** [comment]
Still doesn't seem to work
https://api.subjective.school/v1/transport/times?id=2153190
https://transportnsw.info/trip#/departures?depart=G2153190&type=stop&accessible=false&excludedModes=2,9,11,1,4,7
the subjective api shows the 615X as 6:32 while the transportnsw website shows it as 6:35 and 3 minutes late

<img width="1143" height="317" alt="Image" src="https://github.com/user-attachments/assets/98fea8df-df0e-4091-a7b7-306a31f20045" />

<img width="912" height="628" alt="Image" src="https://github.com/user-attachments/assets/a422670a-00f7-442e-98c6-ac525fe27f58" />

601 is shown by subjectiveapi as 6:36 while the transportnsw says 6:42 and 6 mins late

<img width="841" height="555" alt="Image" src="https://github.com/user-attachments/assets/8bcc22ba-3b4c-4549-8fde-bb0ca0d54976" />

**Comment by the-ethan-wang** [comment]
sorry if it's because the api hasn't updated yet or smth that's not in your control

**Comment by circles-png** [comment]
use the v2 version like `http://api.subjective.school/v2/transport/times?stop_id=2155458&route_id=2504_601`

**Comment by the-ethan-wang** [comment]
ty

**Comment by the-ethan-wang** [comment]
ty
